name: Selenium with TestNG - CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
    
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
      
      - name: Build project
        run: mvn -f autdemo/pom.xml clean install

      - name: Run E2E Tests
        run: mvn -B clean test

      - name: Make InstallChrome.sh executable
        run: chmod +x scripts/InstallChrome.sh

      - name: Run InstallChrome.sh
        run: scripts/InstallChrome.sh

