name: Selenium with TestNG - CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
    
      - name: Set up Chrome
        uses: nanasess/setup-chromedriver@v2 #browser-actions/setup-chrome@latest
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '94.0.4606.61'

      - name: Make InstallChrome.sh executable
        run: chmod +x ./scripts/installChrome.sh

      - name: Run InstallChrome.sh
        run: ./scripts/installChrome.sh

      - name: Build project
        run: mvn -f autdemo/pom.xml clean install

      - name: Run E2E Tests
        run: mvn -B clean test

