name: E2E Tests

on:
  push:
    branches:
      - master

jobs:
  e2e_tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build project
        run: mvn -f ../../POM.xml clean install
        
      - name: Run E2E Tests
        run: mvn test
